apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: personal-projects
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: ent
          - name: POSTGRES_PASSWORD
            value: "password"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgres
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: grocerylistsbot-postgres
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grocerylistsbot-postgres
  namespace: personal-projects
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grocerylistsbot-postgres
  namespace: personal-projects
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgres
