// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jaredallard/grocerylistsbot/ent/groceryitem"
	"github.com/jaredallard/grocerylistsbot/ent/grocerylist"
	"github.com/jaredallard/grocerylistsbot/ent/predicate"
)

// GroceryItemUpdate is the builder for updating GroceryItem entities.
type GroceryItemUpdate struct {
	config
	hooks      []Hook
	mutation   *GroceryItemMutation
	predicates []predicate.GroceryItem
}

// Where adds a new predicate for the builder.
func (giu *GroceryItemUpdate) Where(ps ...predicate.GroceryItem) *GroceryItemUpdate {
	giu.predicates = append(giu.predicates, ps...)
	return giu
}

// SetCreatedAt sets the created_at field.
func (giu *GroceryItemUpdate) SetCreatedAt(t time.Time) *GroceryItemUpdate {
	giu.mutation.SetCreatedAt(t)
	return giu
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (giu *GroceryItemUpdate) SetNillableCreatedAt(t *time.Time) *GroceryItemUpdate {
	if t != nil {
		giu.SetCreatedAt(*t)
	}
	return giu
}

// SetModifiedAt sets the modified_at field.
func (giu *GroceryItemUpdate) SetModifiedAt(t time.Time) *GroceryItemUpdate {
	giu.mutation.SetModifiedAt(t)
	return giu
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (giu *GroceryItemUpdate) SetNillableModifiedAt(t *time.Time) *GroceryItemUpdate {
	if t != nil {
		giu.SetModifiedAt(*t)
	}
	return giu
}

// SetDeletedAt sets the deleted_at field.
func (giu *GroceryItemUpdate) SetDeletedAt(t time.Time) *GroceryItemUpdate {
	giu.mutation.SetDeletedAt(t)
	return giu
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (giu *GroceryItemUpdate) SetNillableDeletedAt(t *time.Time) *GroceryItemUpdate {
	if t != nil {
		giu.SetDeletedAt(*t)
	}
	return giu
}

// ClearDeletedAt clears the value of deleted_at.
func (giu *GroceryItemUpdate) ClearDeletedAt() *GroceryItemUpdate {
	giu.mutation.ClearDeletedAt()
	return giu
}

// SetName sets the name field.
func (giu *GroceryItemUpdate) SetName(s string) *GroceryItemUpdate {
	giu.mutation.SetName(s)
	return giu
}

// SetStatus sets the status field.
func (giu *GroceryItemUpdate) SetStatus(gr groceryitem.Status) *GroceryItemUpdate {
	giu.mutation.SetStatus(gr)
	return giu
}

// SetNillableStatus sets the status field if the given value is not nil.
func (giu *GroceryItemUpdate) SetNillableStatus(gr *groceryitem.Status) *GroceryItemUpdate {
	if gr != nil {
		giu.SetStatus(*gr)
	}
	return giu
}

// SetPrice sets the price field.
func (giu *GroceryItemUpdate) SetPrice(f float64) *GroceryItemUpdate {
	giu.mutation.ResetPrice()
	giu.mutation.SetPrice(f)
	return giu
}

// SetNillablePrice sets the price field if the given value is not nil.
func (giu *GroceryItemUpdate) SetNillablePrice(f *float64) *GroceryItemUpdate {
	if f != nil {
		giu.SetPrice(*f)
	}
	return giu
}

// AddPrice adds f to price.
func (giu *GroceryItemUpdate) AddPrice(f float64) *GroceryItemUpdate {
	giu.mutation.AddPrice(f)
	return giu
}

// ClearPrice clears the value of price.
func (giu *GroceryItemUpdate) ClearPrice() *GroceryItemUpdate {
	giu.mutation.ClearPrice()
	return giu
}

// SetGrocerylistID sets the grocerylist edge to GroceryList by id.
func (giu *GroceryItemUpdate) SetGrocerylistID(id int) *GroceryItemUpdate {
	giu.mutation.SetGrocerylistID(id)
	return giu
}

// SetNillableGrocerylistID sets the grocerylist edge to GroceryList by id if the given value is not nil.
func (giu *GroceryItemUpdate) SetNillableGrocerylistID(id *int) *GroceryItemUpdate {
	if id != nil {
		giu = giu.SetGrocerylistID(*id)
	}
	return giu
}

// SetGrocerylist sets the grocerylist edge to GroceryList.
func (giu *GroceryItemUpdate) SetGrocerylist(g *GroceryList) *GroceryItemUpdate {
	return giu.SetGrocerylistID(g.ID)
}

// ClearGrocerylist clears the grocerylist edge to GroceryList.
func (giu *GroceryItemUpdate) ClearGrocerylist() *GroceryItemUpdate {
	giu.mutation.ClearGrocerylist()
	return giu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (giu *GroceryItemUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := giu.mutation.Status(); ok {
		if err := groceryitem.StatusValidator(v); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"status\": %v", err)
		}
	}

	var (
		err      error
		affected int
	)
	if len(giu.hooks) == 0 {
		affected, err = giu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroceryItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			giu.mutation = mutation
			affected, err = giu.sqlSave(ctx)
			return affected, err
		})
		for i := len(giu.hooks) - 1; i >= 0; i-- {
			mut = giu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, giu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (giu *GroceryItemUpdate) SaveX(ctx context.Context) int {
	affected, err := giu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (giu *GroceryItemUpdate) Exec(ctx context.Context) error {
	_, err := giu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (giu *GroceryItemUpdate) ExecX(ctx context.Context) {
	if err := giu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (giu *GroceryItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groceryitem.Table,
			Columns: groceryitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groceryitem.FieldID,
			},
		},
	}
	if ps := giu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := giu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldCreatedAt,
		})
	}
	if value, ok := giu.mutation.ModifiedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldModifiedAt,
		})
	}
	if value, ok := giu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldDeletedAt,
		})
	}
	if giu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: groceryitem.FieldDeletedAt,
		})
	}
	if value, ok := giu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groceryitem.FieldName,
		})
	}
	if value, ok := giu.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: groceryitem.FieldStatus,
		})
	}
	if value, ok := giu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: groceryitem.FieldPrice,
		})
	}
	if value, ok := giu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: groceryitem.FieldPrice,
		})
	}
	if giu.mutation.PriceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Column: groceryitem.FieldPrice,
		})
	}
	if giu.mutation.GrocerylistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groceryitem.GrocerylistTable,
			Columns: []string{groceryitem.GrocerylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: grocerylist.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := giu.mutation.GrocerylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groceryitem.GrocerylistTable,
			Columns: []string{groceryitem.GrocerylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: grocerylist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, giu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groceryitem.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// GroceryItemUpdateOne is the builder for updating a single GroceryItem entity.
type GroceryItemUpdateOne struct {
	config
	hooks    []Hook
	mutation *GroceryItemMutation
}

// SetCreatedAt sets the created_at field.
func (giuo *GroceryItemUpdateOne) SetCreatedAt(t time.Time) *GroceryItemUpdateOne {
	giuo.mutation.SetCreatedAt(t)
	return giuo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (giuo *GroceryItemUpdateOne) SetNillableCreatedAt(t *time.Time) *GroceryItemUpdateOne {
	if t != nil {
		giuo.SetCreatedAt(*t)
	}
	return giuo
}

// SetModifiedAt sets the modified_at field.
func (giuo *GroceryItemUpdateOne) SetModifiedAt(t time.Time) *GroceryItemUpdateOne {
	giuo.mutation.SetModifiedAt(t)
	return giuo
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (giuo *GroceryItemUpdateOne) SetNillableModifiedAt(t *time.Time) *GroceryItemUpdateOne {
	if t != nil {
		giuo.SetModifiedAt(*t)
	}
	return giuo
}

// SetDeletedAt sets the deleted_at field.
func (giuo *GroceryItemUpdateOne) SetDeletedAt(t time.Time) *GroceryItemUpdateOne {
	giuo.mutation.SetDeletedAt(t)
	return giuo
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (giuo *GroceryItemUpdateOne) SetNillableDeletedAt(t *time.Time) *GroceryItemUpdateOne {
	if t != nil {
		giuo.SetDeletedAt(*t)
	}
	return giuo
}

// ClearDeletedAt clears the value of deleted_at.
func (giuo *GroceryItemUpdateOne) ClearDeletedAt() *GroceryItemUpdateOne {
	giuo.mutation.ClearDeletedAt()
	return giuo
}

// SetName sets the name field.
func (giuo *GroceryItemUpdateOne) SetName(s string) *GroceryItemUpdateOne {
	giuo.mutation.SetName(s)
	return giuo
}

// SetStatus sets the status field.
func (giuo *GroceryItemUpdateOne) SetStatus(gr groceryitem.Status) *GroceryItemUpdateOne {
	giuo.mutation.SetStatus(gr)
	return giuo
}

// SetNillableStatus sets the status field if the given value is not nil.
func (giuo *GroceryItemUpdateOne) SetNillableStatus(gr *groceryitem.Status) *GroceryItemUpdateOne {
	if gr != nil {
		giuo.SetStatus(*gr)
	}
	return giuo
}

// SetPrice sets the price field.
func (giuo *GroceryItemUpdateOne) SetPrice(f float64) *GroceryItemUpdateOne {
	giuo.mutation.ResetPrice()
	giuo.mutation.SetPrice(f)
	return giuo
}

// SetNillablePrice sets the price field if the given value is not nil.
func (giuo *GroceryItemUpdateOne) SetNillablePrice(f *float64) *GroceryItemUpdateOne {
	if f != nil {
		giuo.SetPrice(*f)
	}
	return giuo
}

// AddPrice adds f to price.
func (giuo *GroceryItemUpdateOne) AddPrice(f float64) *GroceryItemUpdateOne {
	giuo.mutation.AddPrice(f)
	return giuo
}

// ClearPrice clears the value of price.
func (giuo *GroceryItemUpdateOne) ClearPrice() *GroceryItemUpdateOne {
	giuo.mutation.ClearPrice()
	return giuo
}

// SetGrocerylistID sets the grocerylist edge to GroceryList by id.
func (giuo *GroceryItemUpdateOne) SetGrocerylistID(id int) *GroceryItemUpdateOne {
	giuo.mutation.SetGrocerylistID(id)
	return giuo
}

// SetNillableGrocerylistID sets the grocerylist edge to GroceryList by id if the given value is not nil.
func (giuo *GroceryItemUpdateOne) SetNillableGrocerylistID(id *int) *GroceryItemUpdateOne {
	if id != nil {
		giuo = giuo.SetGrocerylistID(*id)
	}
	return giuo
}

// SetGrocerylist sets the grocerylist edge to GroceryList.
func (giuo *GroceryItemUpdateOne) SetGrocerylist(g *GroceryList) *GroceryItemUpdateOne {
	return giuo.SetGrocerylistID(g.ID)
}

// ClearGrocerylist clears the grocerylist edge to GroceryList.
func (giuo *GroceryItemUpdateOne) ClearGrocerylist() *GroceryItemUpdateOne {
	giuo.mutation.ClearGrocerylist()
	return giuo
}

// Save executes the query and returns the updated entity.
func (giuo *GroceryItemUpdateOne) Save(ctx context.Context) (*GroceryItem, error) {
	if v, ok := giuo.mutation.Status(); ok {
		if err := groceryitem.StatusValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"status\": %v", err)
		}
	}

	var (
		err  error
		node *GroceryItem
	)
	if len(giuo.hooks) == 0 {
		node, err = giuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroceryItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			giuo.mutation = mutation
			node, err = giuo.sqlSave(ctx)
			return node, err
		})
		for i := len(giuo.hooks) - 1; i >= 0; i-- {
			mut = giuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, giuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (giuo *GroceryItemUpdateOne) SaveX(ctx context.Context) *GroceryItem {
	gi, err := giuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return gi
}

// Exec executes the query on the entity.
func (giuo *GroceryItemUpdateOne) Exec(ctx context.Context) error {
	_, err := giuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (giuo *GroceryItemUpdateOne) ExecX(ctx context.Context) {
	if err := giuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (giuo *GroceryItemUpdateOne) sqlSave(ctx context.Context) (gi *GroceryItem, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groceryitem.Table,
			Columns: groceryitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groceryitem.FieldID,
			},
		},
	}
	id, ok := giuo.mutation.ID()
	if !ok {
		return nil, fmt.Errorf("missing GroceryItem.ID for update")
	}
	_spec.Node.ID.Value = id
	if value, ok := giuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldCreatedAt,
		})
	}
	if value, ok := giuo.mutation.ModifiedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldModifiedAt,
		})
	}
	if value, ok := giuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldDeletedAt,
		})
	}
	if giuo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: groceryitem.FieldDeletedAt,
		})
	}
	if value, ok := giuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groceryitem.FieldName,
		})
	}
	if value, ok := giuo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: groceryitem.FieldStatus,
		})
	}
	if value, ok := giuo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: groceryitem.FieldPrice,
		})
	}
	if value, ok := giuo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: groceryitem.FieldPrice,
		})
	}
	if giuo.mutation.PriceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Column: groceryitem.FieldPrice,
		})
	}
	if giuo.mutation.GrocerylistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groceryitem.GrocerylistTable,
			Columns: []string{groceryitem.GrocerylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: grocerylist.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := giuo.mutation.GrocerylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groceryitem.GrocerylistTable,
			Columns: []string{groceryitem.GrocerylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: grocerylist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	gi = &GroceryItem{config: giuo.config}
	_spec.Assign = gi.assignValues
	_spec.ScanValues = gi.scanValues()
	if err = sqlgraph.UpdateNode(ctx, giuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groceryitem.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return gi, nil
}
