// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jaredallard/grocerylistsbot/ent/groceryitem"
	"github.com/jaredallard/grocerylistsbot/ent/grocerylist"
)

// GroceryItemCreate is the builder for creating a GroceryItem entity.
type GroceryItemCreate struct {
	config
	mutation *GroceryItemMutation
	hooks    []Hook
}

// SetCreatedAt sets the created_at field.
func (gic *GroceryItemCreate) SetCreatedAt(t time.Time) *GroceryItemCreate {
	gic.mutation.SetCreatedAt(t)
	return gic
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (gic *GroceryItemCreate) SetNillableCreatedAt(t *time.Time) *GroceryItemCreate {
	if t != nil {
		gic.SetCreatedAt(*t)
	}
	return gic
}

// SetModifiedAt sets the modified_at field.
func (gic *GroceryItemCreate) SetModifiedAt(t time.Time) *GroceryItemCreate {
	gic.mutation.SetModifiedAt(t)
	return gic
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (gic *GroceryItemCreate) SetNillableModifiedAt(t *time.Time) *GroceryItemCreate {
	if t != nil {
		gic.SetModifiedAt(*t)
	}
	return gic
}

// SetDeletedAt sets the deleted_at field.
func (gic *GroceryItemCreate) SetDeletedAt(t time.Time) *GroceryItemCreate {
	gic.mutation.SetDeletedAt(t)
	return gic
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (gic *GroceryItemCreate) SetNillableDeletedAt(t *time.Time) *GroceryItemCreate {
	if t != nil {
		gic.SetDeletedAt(*t)
	}
	return gic
}

// SetName sets the name field.
func (gic *GroceryItemCreate) SetName(s string) *GroceryItemCreate {
	gic.mutation.SetName(s)
	return gic
}

// SetStatus sets the status field.
func (gic *GroceryItemCreate) SetStatus(gr groceryitem.Status) *GroceryItemCreate {
	gic.mutation.SetStatus(gr)
	return gic
}

// SetNillableStatus sets the status field if the given value is not nil.
func (gic *GroceryItemCreate) SetNillableStatus(gr *groceryitem.Status) *GroceryItemCreate {
	if gr != nil {
		gic.SetStatus(*gr)
	}
	return gic
}

// SetPrice sets the price field.
func (gic *GroceryItemCreate) SetPrice(f float64) *GroceryItemCreate {
	gic.mutation.SetPrice(f)
	return gic
}

// SetNillablePrice sets the price field if the given value is not nil.
func (gic *GroceryItemCreate) SetNillablePrice(f *float64) *GroceryItemCreate {
	if f != nil {
		gic.SetPrice(*f)
	}
	return gic
}

// SetGrocerylistID sets the grocerylist edge to GroceryList by id.
func (gic *GroceryItemCreate) SetGrocerylistID(id int) *GroceryItemCreate {
	gic.mutation.SetGrocerylistID(id)
	return gic
}

// SetNillableGrocerylistID sets the grocerylist edge to GroceryList by id if the given value is not nil.
func (gic *GroceryItemCreate) SetNillableGrocerylistID(id *int) *GroceryItemCreate {
	if id != nil {
		gic = gic.SetGrocerylistID(*id)
	}
	return gic
}

// SetGrocerylist sets the grocerylist edge to GroceryList.
func (gic *GroceryItemCreate) SetGrocerylist(g *GroceryList) *GroceryItemCreate {
	return gic.SetGrocerylistID(g.ID)
}

// Save creates the GroceryItem in the database.
func (gic *GroceryItemCreate) Save(ctx context.Context) (*GroceryItem, error) {
	if _, ok := gic.mutation.CreatedAt(); !ok {
		v := groceryitem.DefaultCreatedAt()
		gic.mutation.SetCreatedAt(v)
	}
	if _, ok := gic.mutation.ModifiedAt(); !ok {
		v := groceryitem.DefaultModifiedAt()
		gic.mutation.SetModifiedAt(v)
	}
	if _, ok := gic.mutation.Name(); !ok {
		return nil, errors.New("ent: missing required field \"name\"")
	}
	if _, ok := gic.mutation.Status(); !ok {
		v := groceryitem.DefaultStatus
		gic.mutation.SetStatus(v)
	}
	if v, ok := gic.mutation.Status(); ok {
		if err := groceryitem.StatusValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"status\": %v", err)
		}
	}
	var (
		err  error
		node *GroceryItem
	)
	if len(gic.hooks) == 0 {
		node, err = gic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroceryItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gic.mutation = mutation
			node, err = gic.sqlSave(ctx)
			return node, err
		})
		for i := len(gic.hooks) - 1; i >= 0; i-- {
			mut = gic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gic *GroceryItemCreate) SaveX(ctx context.Context) *GroceryItem {
	v, err := gic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gic *GroceryItemCreate) sqlSave(ctx context.Context) (*GroceryItem, error) {
	var (
		gi    = &GroceryItem{config: gic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: groceryitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groceryitem.FieldID,
			},
		}
	)
	if value, ok := gic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldCreatedAt,
		})
		gi.CreatedAt = value
	}
	if value, ok := gic.mutation.ModifiedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldModifiedAt,
		})
		gi.ModifiedAt = value
	}
	if value, ok := gic.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groceryitem.FieldDeletedAt,
		})
		gi.DeletedAt = &value
	}
	if value, ok := gic.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groceryitem.FieldName,
		})
		gi.Name = value
	}
	if value, ok := gic.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: groceryitem.FieldStatus,
		})
		gi.Status = value
	}
	if value, ok := gic.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: groceryitem.FieldPrice,
		})
		gi.Price = value
	}
	if nodes := gic.mutation.GrocerylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groceryitem.GrocerylistTable,
			Columns: []string{groceryitem.GrocerylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: grocerylist.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, gic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	gi.ID = int(id)
	return gi, nil
}
