// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jaredallard/grocerylistsbot/ent/groceryitem"
	"github.com/jaredallard/grocerylistsbot/ent/grocerylist"
	"github.com/jaredallard/grocerylistsbot/ent/predicate"
)

// GroceryItemQuery is the builder for querying GroceryItem entities.
type GroceryItemQuery struct {
	config
	limit      *int
	offset     *int
	order      []Order
	unique     []string
	predicates []predicate.GroceryItem
	// eager-loading edges.
	withGrocerylist *GroceryListQuery
	withFKs         bool
	// intermediate query.
	sql *sql.Selector
}

// Where adds a new predicate for the builder.
func (giq *GroceryItemQuery) Where(ps ...predicate.GroceryItem) *GroceryItemQuery {
	giq.predicates = append(giq.predicates, ps...)
	return giq
}

// Limit adds a limit step to the query.
func (giq *GroceryItemQuery) Limit(limit int) *GroceryItemQuery {
	giq.limit = &limit
	return giq
}

// Offset adds an offset step to the query.
func (giq *GroceryItemQuery) Offset(offset int) *GroceryItemQuery {
	giq.offset = &offset
	return giq
}

// Order adds an order step to the query.
func (giq *GroceryItemQuery) Order(o ...Order) *GroceryItemQuery {
	giq.order = append(giq.order, o...)
	return giq
}

// QueryGrocerylist chains the current query on the grocerylist edge.
func (giq *GroceryItemQuery) QueryGrocerylist() *GroceryListQuery {
	query := &GroceryListQuery{config: giq.config}
	step := sqlgraph.NewStep(
		sqlgraph.From(groceryitem.Table, groceryitem.FieldID, giq.sqlQuery()),
		sqlgraph.To(grocerylist.Table, grocerylist.FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, groceryitem.GrocerylistTable, groceryitem.GrocerylistColumn),
	)
	query.sql = sqlgraph.SetNeighbors(giq.driver.Dialect(), step)
	return query
}

// First returns the first GroceryItem entity in the query. Returns *NotFoundError when no groceryitem was found.
func (giq *GroceryItemQuery) First(ctx context.Context) (*GroceryItem, error) {
	gis, err := giq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(gis) == 0 {
		return nil, &NotFoundError{groceryitem.Label}
	}
	return gis[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (giq *GroceryItemQuery) FirstX(ctx context.Context) *GroceryItem {
	gi, err := giq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return gi
}

// FirstID returns the first GroceryItem id in the query. Returns *NotFoundError when no id was found.
func (giq *GroceryItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = giq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groceryitem.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (giq *GroceryItemQuery) FirstXID(ctx context.Context) int {
	id, err := giq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only GroceryItem entity in the query, returns an error if not exactly one entity was returned.
func (giq *GroceryItemQuery) Only(ctx context.Context) (*GroceryItem, error) {
	gis, err := giq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(gis) {
	case 1:
		return gis[0], nil
	case 0:
		return nil, &NotFoundError{groceryitem.Label}
	default:
		return nil, &NotSingularError{groceryitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (giq *GroceryItemQuery) OnlyX(ctx context.Context) *GroceryItem {
	gi, err := giq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return gi
}

// OnlyID returns the only GroceryItem id in the query, returns an error if not exactly one id was returned.
func (giq *GroceryItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = giq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groceryitem.Label}
	default:
		err = &NotSingularError{groceryitem.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (giq *GroceryItemQuery) OnlyXID(ctx context.Context) int {
	id, err := giq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroceryItems.
func (giq *GroceryItemQuery) All(ctx context.Context) ([]*GroceryItem, error) {
	return giq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (giq *GroceryItemQuery) AllX(ctx context.Context) []*GroceryItem {
	gis, err := giq.All(ctx)
	if err != nil {
		panic(err)
	}
	return gis
}

// IDs executes the query and returns a list of GroceryItem ids.
func (giq *GroceryItemQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := giq.Select(groceryitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (giq *GroceryItemQuery) IDsX(ctx context.Context) []int {
	ids, err := giq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (giq *GroceryItemQuery) Count(ctx context.Context) (int, error) {
	return giq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (giq *GroceryItemQuery) CountX(ctx context.Context) int {
	count, err := giq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (giq *GroceryItemQuery) Exist(ctx context.Context) (bool, error) {
	return giq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (giq *GroceryItemQuery) ExistX(ctx context.Context) bool {
	exist, err := giq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (giq *GroceryItemQuery) Clone() *GroceryItemQuery {
	return &GroceryItemQuery{
		config:     giq.config,
		limit:      giq.limit,
		offset:     giq.offset,
		order:      append([]Order{}, giq.order...),
		unique:     append([]string{}, giq.unique...),
		predicates: append([]predicate.GroceryItem{}, giq.predicates...),
		// clone intermediate query.
		sql: giq.sql.Clone(),
	}
}

//  WithGrocerylist tells the query-builder to eager-loads the nodes that are connected to
// the "grocerylist" edge. The optional arguments used to configure the query builder of the edge.
func (giq *GroceryItemQuery) WithGrocerylist(opts ...func(*GroceryListQuery)) *GroceryItemQuery {
	query := &GroceryListQuery{config: giq.config}
	for _, opt := range opts {
		opt(query)
	}
	giq.withGrocerylist = query
	return giq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroceryItem.Query().
//		GroupBy(groceryitem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (giq *GroceryItemQuery) GroupBy(field string, fields ...string) *GroceryItemGroupBy {
	group := &GroceryItemGroupBy{config: giq.config}
	group.fields = append([]string{field}, fields...)
	group.sql = giq.sqlQuery()
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GroceryItem.Query().
//		Select(groceryitem.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (giq *GroceryItemQuery) Select(field string, fields ...string) *GroceryItemSelect {
	selector := &GroceryItemSelect{config: giq.config}
	selector.fields = append([]string{field}, fields...)
	selector.sql = giq.sqlQuery()
	return selector
}

func (giq *GroceryItemQuery) sqlAll(ctx context.Context) ([]*GroceryItem, error) {
	var (
		nodes   []*GroceryItem = []*GroceryItem{}
		withFKs                = giq.withFKs
		_spec                  = giq.querySpec()
	)
	if giq.withGrocerylist != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, groceryitem.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &GroceryItem{config: giq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, giq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := giq.withGrocerylist; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*GroceryItem)
		for i := range nodes {
			if fk := nodes[i].grocery_item_grocerylist_id; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(grocerylist.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "grocery_item_grocerylist_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Grocerylist = n
			}
		}
	}

	return nodes, nil
}

func (giq *GroceryItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := giq.querySpec()
	return sqlgraph.CountNodes(ctx, giq.driver, _spec)
}

func (giq *GroceryItemQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := giq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (giq *GroceryItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groceryitem.Table,
			Columns: groceryitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groceryitem.FieldID,
			},
		},
		From:   giq.sql,
		Unique: true,
	}
	if ps := giq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := giq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := giq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := giq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (giq *GroceryItemQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(giq.driver.Dialect())
	t1 := builder.Table(groceryitem.Table)
	selector := builder.Select(t1.Columns(groceryitem.Columns...)...).From(t1)
	if giq.sql != nil {
		selector = giq.sql
		selector.Select(selector.Columns(groceryitem.Columns...)...)
	}
	for _, p := range giq.predicates {
		p(selector)
	}
	for _, p := range giq.order {
		p(selector)
	}
	if offset := giq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := giq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroceryItemGroupBy is the builder for group-by GroceryItem entities.
type GroceryItemGroupBy struct {
	config
	fields []string
	fns    []Aggregate
	// intermediate query.
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gigb *GroceryItemGroupBy) Aggregate(fns ...Aggregate) *GroceryItemGroupBy {
	gigb.fns = append(gigb.fns, fns...)
	return gigb
}

// Scan applies the group-by query and scan the result into the given value.
func (gigb *GroceryItemGroupBy) Scan(ctx context.Context, v interface{}) error {
	return gigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gigb *GroceryItemGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := gigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (gigb *GroceryItemGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(gigb.fields) > 1 {
		return nil, errors.New("ent: GroceryItemGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := gigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gigb *GroceryItemGroupBy) StringsX(ctx context.Context) []string {
	v, err := gigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (gigb *GroceryItemGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(gigb.fields) > 1 {
		return nil, errors.New("ent: GroceryItemGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := gigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gigb *GroceryItemGroupBy) IntsX(ctx context.Context) []int {
	v, err := gigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (gigb *GroceryItemGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(gigb.fields) > 1 {
		return nil, errors.New("ent: GroceryItemGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := gigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gigb *GroceryItemGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := gigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (gigb *GroceryItemGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(gigb.fields) > 1 {
		return nil, errors.New("ent: GroceryItemGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := gigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gigb *GroceryItemGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := gigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gigb *GroceryItemGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gigb.sqlQuery().Query()
	if err := gigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gigb *GroceryItemGroupBy) sqlQuery() *sql.Selector {
	selector := gigb.sql
	columns := make([]string, 0, len(gigb.fields)+len(gigb.fns))
	columns = append(columns, gigb.fields...)
	for _, fn := range gigb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(gigb.fields...)
}

// GroceryItemSelect is the builder for select fields of GroceryItem entities.
type GroceryItemSelect struct {
	config
	fields []string
	// intermediate queries.
	sql *sql.Selector
}

// Scan applies the selector query and scan the result into the given value.
func (gis *GroceryItemSelect) Scan(ctx context.Context, v interface{}) error {
	return gis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gis *GroceryItemSelect) ScanX(ctx context.Context, v interface{}) {
	if err := gis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (gis *GroceryItemSelect) Strings(ctx context.Context) ([]string, error) {
	if len(gis.fields) > 1 {
		return nil, errors.New("ent: GroceryItemSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := gis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gis *GroceryItemSelect) StringsX(ctx context.Context) []string {
	v, err := gis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (gis *GroceryItemSelect) Ints(ctx context.Context) ([]int, error) {
	if len(gis.fields) > 1 {
		return nil, errors.New("ent: GroceryItemSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := gis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gis *GroceryItemSelect) IntsX(ctx context.Context) []int {
	v, err := gis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (gis *GroceryItemSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(gis.fields) > 1 {
		return nil, errors.New("ent: GroceryItemSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := gis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gis *GroceryItemSelect) Float64sX(ctx context.Context) []float64 {
	v, err := gis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (gis *GroceryItemSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(gis.fields) > 1 {
		return nil, errors.New("ent: GroceryItemSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := gis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gis *GroceryItemSelect) BoolsX(ctx context.Context) []bool {
	v, err := gis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gis *GroceryItemSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gis.sqlQuery().Query()
	if err := gis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gis *GroceryItemSelect) sqlQuery() sql.Querier {
	selector := gis.sql
	selector.Select(selector.Columns(gis.fields...)...)
	return selector
}
