// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jaredallard/grocerylistsbot/ent/grocerylist"
	"github.com/jaredallard/grocerylistsbot/ent/predicate"
	"github.com/jaredallard/grocerylistsbot/ent/user"
)

// GroceryListUpdate is the builder for updating GroceryList entities.
type GroceryListUpdate struct {
	config
	hooks      []Hook
	mutation   *GroceryListMutation
	predicates []predicate.GroceryList
}

// Where adds a new predicate for the builder.
func (glu *GroceryListUpdate) Where(ps ...predicate.GroceryList) *GroceryListUpdate {
	glu.predicates = append(glu.predicates, ps...)
	return glu
}

// SetCreatedAt sets the created_at field.
func (glu *GroceryListUpdate) SetCreatedAt(t time.Time) *GroceryListUpdate {
	glu.mutation.SetCreatedAt(t)
	return glu
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (glu *GroceryListUpdate) SetNillableCreatedAt(t *time.Time) *GroceryListUpdate {
	if t != nil {
		glu.SetCreatedAt(*t)
	}
	return glu
}

// SetModifiedAt sets the modified_at field.
func (glu *GroceryListUpdate) SetModifiedAt(t time.Time) *GroceryListUpdate {
	glu.mutation.SetModifiedAt(t)
	return glu
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (glu *GroceryListUpdate) SetNillableModifiedAt(t *time.Time) *GroceryListUpdate {
	if t != nil {
		glu.SetModifiedAt(*t)
	}
	return glu
}

// SetDeletedAt sets the deleted_at field.
func (glu *GroceryListUpdate) SetDeletedAt(t time.Time) *GroceryListUpdate {
	glu.mutation.SetDeletedAt(t)
	return glu
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (glu *GroceryListUpdate) SetNillableDeletedAt(t *time.Time) *GroceryListUpdate {
	if t != nil {
		glu.SetDeletedAt(*t)
	}
	return glu
}

// ClearDeletedAt clears the value of deleted_at.
func (glu *GroceryListUpdate) ClearDeletedAt() *GroceryListUpdate {
	glu.mutation.ClearDeletedAt()
	return glu
}

// SetName sets the name field.
func (glu *GroceryListUpdate) SetName(s string) *GroceryListUpdate {
	glu.mutation.SetName(s)
	return glu
}

// SetNillableName sets the name field if the given value is not nil.
func (glu *GroceryListUpdate) SetNillableName(s *string) *GroceryListUpdate {
	if s != nil {
		glu.SetName(*s)
	}
	return glu
}

// AddMemberIDs adds the members edge to User by ids.
func (glu *GroceryListUpdate) AddMemberIDs(ids ...int) *GroceryListUpdate {
	glu.mutation.AddMemberIDs(ids...)
	return glu
}

// AddMembers adds the members edges to User.
func (glu *GroceryListUpdate) AddMembers(u ...*User) *GroceryListUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return glu.AddMemberIDs(ids...)
}

// RemoveMemberIDs removes the members edge to User by ids.
func (glu *GroceryListUpdate) RemoveMemberIDs(ids ...int) *GroceryListUpdate {
	glu.mutation.RemoveMemberIDs(ids...)
	return glu
}

// RemoveMembers removes members edges to User.
func (glu *GroceryListUpdate) RemoveMembers(u ...*User) *GroceryListUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return glu.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (glu *GroceryListUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(glu.hooks) == 0 {
		affected, err = glu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroceryListMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			glu.mutation = mutation
			affected, err = glu.sqlSave(ctx)
			return affected, err
		})
		for i := len(glu.hooks) - 1; i >= 0; i-- {
			mut = glu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, glu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (glu *GroceryListUpdate) SaveX(ctx context.Context) int {
	affected, err := glu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (glu *GroceryListUpdate) Exec(ctx context.Context) error {
	_, err := glu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (glu *GroceryListUpdate) ExecX(ctx context.Context) {
	if err := glu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (glu *GroceryListUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   grocerylist.Table,
			Columns: grocerylist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: grocerylist.FieldID,
			},
		},
	}
	if ps := glu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := glu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: grocerylist.FieldCreatedAt,
		})
	}
	if value, ok := glu.mutation.ModifiedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: grocerylist.FieldModifiedAt,
		})
	}
	if value, ok := glu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: grocerylist.FieldDeletedAt,
		})
	}
	if glu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: grocerylist.FieldDeletedAt,
		})
	}
	if value, ok := glu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: grocerylist.FieldName,
		})
	}
	if nodes := glu.mutation.RemovedMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   grocerylist.MembersTable,
			Columns: grocerylist.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := glu.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   grocerylist.MembersTable,
			Columns: grocerylist.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, glu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grocerylist.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// GroceryListUpdateOne is the builder for updating a single GroceryList entity.
type GroceryListUpdateOne struct {
	config
	hooks    []Hook
	mutation *GroceryListMutation
}

// SetCreatedAt sets the created_at field.
func (gluo *GroceryListUpdateOne) SetCreatedAt(t time.Time) *GroceryListUpdateOne {
	gluo.mutation.SetCreatedAt(t)
	return gluo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (gluo *GroceryListUpdateOne) SetNillableCreatedAt(t *time.Time) *GroceryListUpdateOne {
	if t != nil {
		gluo.SetCreatedAt(*t)
	}
	return gluo
}

// SetModifiedAt sets the modified_at field.
func (gluo *GroceryListUpdateOne) SetModifiedAt(t time.Time) *GroceryListUpdateOne {
	gluo.mutation.SetModifiedAt(t)
	return gluo
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (gluo *GroceryListUpdateOne) SetNillableModifiedAt(t *time.Time) *GroceryListUpdateOne {
	if t != nil {
		gluo.SetModifiedAt(*t)
	}
	return gluo
}

// SetDeletedAt sets the deleted_at field.
func (gluo *GroceryListUpdateOne) SetDeletedAt(t time.Time) *GroceryListUpdateOne {
	gluo.mutation.SetDeletedAt(t)
	return gluo
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (gluo *GroceryListUpdateOne) SetNillableDeletedAt(t *time.Time) *GroceryListUpdateOne {
	if t != nil {
		gluo.SetDeletedAt(*t)
	}
	return gluo
}

// ClearDeletedAt clears the value of deleted_at.
func (gluo *GroceryListUpdateOne) ClearDeletedAt() *GroceryListUpdateOne {
	gluo.mutation.ClearDeletedAt()
	return gluo
}

// SetName sets the name field.
func (gluo *GroceryListUpdateOne) SetName(s string) *GroceryListUpdateOne {
	gluo.mutation.SetName(s)
	return gluo
}

// SetNillableName sets the name field if the given value is not nil.
func (gluo *GroceryListUpdateOne) SetNillableName(s *string) *GroceryListUpdateOne {
	if s != nil {
		gluo.SetName(*s)
	}
	return gluo
}

// AddMemberIDs adds the members edge to User by ids.
func (gluo *GroceryListUpdateOne) AddMemberIDs(ids ...int) *GroceryListUpdateOne {
	gluo.mutation.AddMemberIDs(ids...)
	return gluo
}

// AddMembers adds the members edges to User.
func (gluo *GroceryListUpdateOne) AddMembers(u ...*User) *GroceryListUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gluo.AddMemberIDs(ids...)
}

// RemoveMemberIDs removes the members edge to User by ids.
func (gluo *GroceryListUpdateOne) RemoveMemberIDs(ids ...int) *GroceryListUpdateOne {
	gluo.mutation.RemoveMemberIDs(ids...)
	return gluo
}

// RemoveMembers removes members edges to User.
func (gluo *GroceryListUpdateOne) RemoveMembers(u ...*User) *GroceryListUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gluo.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (gluo *GroceryListUpdateOne) Save(ctx context.Context) (*GroceryList, error) {

	var (
		err  error
		node *GroceryList
	)
	if len(gluo.hooks) == 0 {
		node, err = gluo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroceryListMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gluo.mutation = mutation
			node, err = gluo.sqlSave(ctx)
			return node, err
		})
		for i := len(gluo.hooks) - 1; i >= 0; i-- {
			mut = gluo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gluo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (gluo *GroceryListUpdateOne) SaveX(ctx context.Context) *GroceryList {
	gl, err := gluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return gl
}

// Exec executes the query on the entity.
func (gluo *GroceryListUpdateOne) Exec(ctx context.Context) error {
	_, err := gluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gluo *GroceryListUpdateOne) ExecX(ctx context.Context) {
	if err := gluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gluo *GroceryListUpdateOne) sqlSave(ctx context.Context) (gl *GroceryList, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   grocerylist.Table,
			Columns: grocerylist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: grocerylist.FieldID,
			},
		},
	}
	id, ok := gluo.mutation.ID()
	if !ok {
		return nil, fmt.Errorf("missing GroceryList.ID for update")
	}
	_spec.Node.ID.Value = id
	if value, ok := gluo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: grocerylist.FieldCreatedAt,
		})
	}
	if value, ok := gluo.mutation.ModifiedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: grocerylist.FieldModifiedAt,
		})
	}
	if value, ok := gluo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: grocerylist.FieldDeletedAt,
		})
	}
	if gluo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: grocerylist.FieldDeletedAt,
		})
	}
	if value, ok := gluo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: grocerylist.FieldName,
		})
	}
	if nodes := gluo.mutation.RemovedMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   grocerylist.MembersTable,
			Columns: grocerylist.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gluo.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   grocerylist.MembersTable,
			Columns: grocerylist.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	gl = &GroceryList{config: gluo.config}
	_spec.Assign = gl.assignValues
	_spec.ScanValues = gl.scanValues()
	if err = sqlgraph.UpdateNode(ctx, gluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grocerylist.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return gl, nil
}
