// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/jaredallard/grocerylistsbot/ent/groceryitem"
	"github.com/jaredallard/grocerylistsbot/ent/grocerylist"
	"github.com/jaredallard/grocerylistsbot/ent/schema"
	"github.com/jaredallard/grocerylistsbot/ent/user"
	"github.com/jaredallard/grocerylistsbot/ent/useridmapping"

	"github.com/facebookincubator/ent"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	groceryitemMixin := schema.GroceryItem{}.Mixin()
	groceryitemMixinFields := [...][]ent.Field{
		groceryitemMixin[0].Fields(),
	}
	groceryitemFields := schema.GroceryItem{}.Fields()
	_ = groceryitemFields
	// groceryitemDescCreatedAt is the schema descriptor for created_at field.
	groceryitemDescCreatedAt := groceryitemMixinFields[0][0].Descriptor()
	// groceryitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	groceryitem.DefaultCreatedAt = groceryitemDescCreatedAt.Default.(func() time.Time)
	// groceryitemDescModifiedAt is the schema descriptor for modified_at field.
	groceryitemDescModifiedAt := groceryitemMixinFields[0][1].Descriptor()
	// groceryitem.DefaultModifiedAt holds the default value on creation for the modified_at field.
	groceryitem.DefaultModifiedAt = groceryitemDescModifiedAt.Default.(func() time.Time)
	grocerylistMixin := schema.GroceryList{}.Mixin()
	grocerylistMixinFields := [...][]ent.Field{
		grocerylistMixin[0].Fields(),
	}
	grocerylistFields := schema.GroceryList{}.Fields()
	_ = grocerylistFields
	// grocerylistDescCreatedAt is the schema descriptor for created_at field.
	grocerylistDescCreatedAt := grocerylistMixinFields[0][0].Descriptor()
	// grocerylist.DefaultCreatedAt holds the default value on creation for the created_at field.
	grocerylist.DefaultCreatedAt = grocerylistDescCreatedAt.Default.(func() time.Time)
	// grocerylistDescModifiedAt is the schema descriptor for modified_at field.
	grocerylistDescModifiedAt := grocerylistMixinFields[0][1].Descriptor()
	// grocerylist.DefaultModifiedAt holds the default value on creation for the modified_at field.
	grocerylist.DefaultModifiedAt = grocerylistDescModifiedAt.Default.(func() time.Time)
	// grocerylistDescName is the schema descriptor for name field.
	grocerylistDescName := grocerylistFields[0].Descriptor()
	// grocerylist.DefaultName holds the default value on creation for the name field.
	grocerylist.DefaultName = grocerylistDescName.Default.(string)
	userMixin := schema.User{}.Mixin()
	userMixinFields := [...][]ent.Field{
		userMixin[0].Fields(),
	}
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields[0][0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescModifiedAt is the schema descriptor for modified_at field.
	userDescModifiedAt := userMixinFields[0][1].Descriptor()
	// user.DefaultModifiedAt holds the default value on creation for the modified_at field.
	user.DefaultModifiedAt = userDescModifiedAt.Default.(func() time.Time)
	useridmappingMixin := schema.UserIDMapping{}.Mixin()
	useridmappingMixinFields := [...][]ent.Field{
		useridmappingMixin[0].Fields(),
	}
	useridmappingFields := schema.UserIDMapping{}.Fields()
	_ = useridmappingFields
	// useridmappingDescCreatedAt is the schema descriptor for created_at field.
	useridmappingDescCreatedAt := useridmappingMixinFields[0][0].Descriptor()
	// useridmapping.DefaultCreatedAt holds the default value on creation for the created_at field.
	useridmapping.DefaultCreatedAt = useridmappingDescCreatedAt.Default.(func() time.Time)
	// useridmappingDescModifiedAt is the schema descriptor for modified_at field.
	useridmappingDescModifiedAt := useridmappingMixinFields[0][1].Descriptor()
	// useridmapping.DefaultModifiedAt holds the default value on creation for the modified_at field.
	useridmapping.DefaultModifiedAt = useridmappingDescModifiedAt.Default.(func() time.Time)
}
