// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jaredallard/grocerylistsbot/ent/predicate"
	"github.com/jaredallard/grocerylistsbot/ent/user"
	"github.com/jaredallard/grocerylistsbot/ent/useridmapping"
)

// UserIDMappingUpdate is the builder for updating UserIDMapping entities.
type UserIDMappingUpdate struct {
	config
	created_at      *time.Time
	modified_at     *time.Time
	deleted_at      *time.Time
	cleardeleted_at bool
	platform_type   *useridmapping.PlatformType
	platform_id     *string
	user            map[int]struct{}
	clearedUser     bool
	predicates      []predicate.UserIDMapping
}

// Where adds a new predicate for the builder.
func (uimu *UserIDMappingUpdate) Where(ps ...predicate.UserIDMapping) *UserIDMappingUpdate {
	uimu.predicates = append(uimu.predicates, ps...)
	return uimu
}

// SetCreatedAt sets the created_at field.
func (uimu *UserIDMappingUpdate) SetCreatedAt(t time.Time) *UserIDMappingUpdate {
	uimu.created_at = &t
	return uimu
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (uimu *UserIDMappingUpdate) SetNillableCreatedAt(t *time.Time) *UserIDMappingUpdate {
	if t != nil {
		uimu.SetCreatedAt(*t)
	}
	return uimu
}

// SetModifiedAt sets the modified_at field.
func (uimu *UserIDMappingUpdate) SetModifiedAt(t time.Time) *UserIDMappingUpdate {
	uimu.modified_at = &t
	return uimu
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (uimu *UserIDMappingUpdate) SetNillableModifiedAt(t *time.Time) *UserIDMappingUpdate {
	if t != nil {
		uimu.SetModifiedAt(*t)
	}
	return uimu
}

// SetDeletedAt sets the deleted_at field.
func (uimu *UserIDMappingUpdate) SetDeletedAt(t time.Time) *UserIDMappingUpdate {
	uimu.deleted_at = &t
	return uimu
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (uimu *UserIDMappingUpdate) SetNillableDeletedAt(t *time.Time) *UserIDMappingUpdate {
	if t != nil {
		uimu.SetDeletedAt(*t)
	}
	return uimu
}

// ClearDeletedAt clears the value of deleted_at.
func (uimu *UserIDMappingUpdate) ClearDeletedAt() *UserIDMappingUpdate {
	uimu.deleted_at = nil
	uimu.cleardeleted_at = true
	return uimu
}

// SetPlatformType sets the platform_type field.
func (uimu *UserIDMappingUpdate) SetPlatformType(ut useridmapping.PlatformType) *UserIDMappingUpdate {
	uimu.platform_type = &ut
	return uimu
}

// SetPlatformID sets the platform_id field.
func (uimu *UserIDMappingUpdate) SetPlatformID(s string) *UserIDMappingUpdate {
	uimu.platform_id = &s
	return uimu
}

// SetUserID sets the user edge to User by id.
func (uimu *UserIDMappingUpdate) SetUserID(id int) *UserIDMappingUpdate {
	if uimu.user == nil {
		uimu.user = make(map[int]struct{})
	}
	uimu.user[id] = struct{}{}
	return uimu
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (uimu *UserIDMappingUpdate) SetNillableUserID(id *int) *UserIDMappingUpdate {
	if id != nil {
		uimu = uimu.SetUserID(*id)
	}
	return uimu
}

// SetUser sets the user edge to User.
func (uimu *UserIDMappingUpdate) SetUser(u *User) *UserIDMappingUpdate {
	return uimu.SetUserID(u.ID)
}

// ClearUser clears the user edge to User.
func (uimu *UserIDMappingUpdate) ClearUser() *UserIDMappingUpdate {
	uimu.clearedUser = true
	return uimu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uimu *UserIDMappingUpdate) Save(ctx context.Context) (int, error) {
	if uimu.platform_type != nil {
		if err := useridmapping.PlatformTypeValidator(*uimu.platform_type); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"platform_type\": %v", err)
		}
	}
	if len(uimu.user) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"user\"")
	}
	return uimu.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (uimu *UserIDMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := uimu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uimu *UserIDMappingUpdate) Exec(ctx context.Context) error {
	_, err := uimu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uimu *UserIDMappingUpdate) ExecX(ctx context.Context) {
	if err := uimu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uimu *UserIDMappingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useridmapping.Table,
			Columns: useridmapping.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useridmapping.FieldID,
			},
		},
	}
	if ps := uimu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := uimu.created_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: useridmapping.FieldCreatedAt,
		})
	}
	if value := uimu.modified_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: useridmapping.FieldModifiedAt,
		})
	}
	if value := uimu.deleted_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: useridmapping.FieldDeletedAt,
		})
	}
	if uimu.cleardeleted_at {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: useridmapping.FieldDeletedAt,
		})
	}
	if value := uimu.platform_type; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  *value,
			Column: useridmapping.FieldPlatformType,
		})
	}
	if value := uimu.platform_id; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: useridmapping.FieldPlatformID,
		})
	}
	if uimu.clearedUser {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useridmapping.UserTable,
			Columns: []string{useridmapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uimu.user; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useridmapping.UserTable,
			Columns: []string{useridmapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uimu.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserIDMappingUpdateOne is the builder for updating a single UserIDMapping entity.
type UserIDMappingUpdateOne struct {
	config
	id              int
	created_at      *time.Time
	modified_at     *time.Time
	deleted_at      *time.Time
	cleardeleted_at bool
	platform_type   *useridmapping.PlatformType
	platform_id     *string
	user            map[int]struct{}
	clearedUser     bool
}

// SetCreatedAt sets the created_at field.
func (uimuo *UserIDMappingUpdateOne) SetCreatedAt(t time.Time) *UserIDMappingUpdateOne {
	uimuo.created_at = &t
	return uimuo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (uimuo *UserIDMappingUpdateOne) SetNillableCreatedAt(t *time.Time) *UserIDMappingUpdateOne {
	if t != nil {
		uimuo.SetCreatedAt(*t)
	}
	return uimuo
}

// SetModifiedAt sets the modified_at field.
func (uimuo *UserIDMappingUpdateOne) SetModifiedAt(t time.Time) *UserIDMappingUpdateOne {
	uimuo.modified_at = &t
	return uimuo
}

// SetNillableModifiedAt sets the modified_at field if the given value is not nil.
func (uimuo *UserIDMappingUpdateOne) SetNillableModifiedAt(t *time.Time) *UserIDMappingUpdateOne {
	if t != nil {
		uimuo.SetModifiedAt(*t)
	}
	return uimuo
}

// SetDeletedAt sets the deleted_at field.
func (uimuo *UserIDMappingUpdateOne) SetDeletedAt(t time.Time) *UserIDMappingUpdateOne {
	uimuo.deleted_at = &t
	return uimuo
}

// SetNillableDeletedAt sets the deleted_at field if the given value is not nil.
func (uimuo *UserIDMappingUpdateOne) SetNillableDeletedAt(t *time.Time) *UserIDMappingUpdateOne {
	if t != nil {
		uimuo.SetDeletedAt(*t)
	}
	return uimuo
}

// ClearDeletedAt clears the value of deleted_at.
func (uimuo *UserIDMappingUpdateOne) ClearDeletedAt() *UserIDMappingUpdateOne {
	uimuo.deleted_at = nil
	uimuo.cleardeleted_at = true
	return uimuo
}

// SetPlatformType sets the platform_type field.
func (uimuo *UserIDMappingUpdateOne) SetPlatformType(ut useridmapping.PlatformType) *UserIDMappingUpdateOne {
	uimuo.platform_type = &ut
	return uimuo
}

// SetPlatformID sets the platform_id field.
func (uimuo *UserIDMappingUpdateOne) SetPlatformID(s string) *UserIDMappingUpdateOne {
	uimuo.platform_id = &s
	return uimuo
}

// SetUserID sets the user edge to User by id.
func (uimuo *UserIDMappingUpdateOne) SetUserID(id int) *UserIDMappingUpdateOne {
	if uimuo.user == nil {
		uimuo.user = make(map[int]struct{})
	}
	uimuo.user[id] = struct{}{}
	return uimuo
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (uimuo *UserIDMappingUpdateOne) SetNillableUserID(id *int) *UserIDMappingUpdateOne {
	if id != nil {
		uimuo = uimuo.SetUserID(*id)
	}
	return uimuo
}

// SetUser sets the user edge to User.
func (uimuo *UserIDMappingUpdateOne) SetUser(u *User) *UserIDMappingUpdateOne {
	return uimuo.SetUserID(u.ID)
}

// ClearUser clears the user edge to User.
func (uimuo *UserIDMappingUpdateOne) ClearUser() *UserIDMappingUpdateOne {
	uimuo.clearedUser = true
	return uimuo
}

// Save executes the query and returns the updated entity.
func (uimuo *UserIDMappingUpdateOne) Save(ctx context.Context) (*UserIDMapping, error) {
	if uimuo.platform_type != nil {
		if err := useridmapping.PlatformTypeValidator(*uimuo.platform_type); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"platform_type\": %v", err)
		}
	}
	if len(uimuo.user) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"user\"")
	}
	return uimuo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (uimuo *UserIDMappingUpdateOne) SaveX(ctx context.Context) *UserIDMapping {
	uim, err := uimuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return uim
}

// Exec executes the query on the entity.
func (uimuo *UserIDMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := uimuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uimuo *UserIDMappingUpdateOne) ExecX(ctx context.Context) {
	if err := uimuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uimuo *UserIDMappingUpdateOne) sqlSave(ctx context.Context) (uim *UserIDMapping, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useridmapping.Table,
			Columns: useridmapping.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  uimuo.id,
				Type:   field.TypeInt,
				Column: useridmapping.FieldID,
			},
		},
	}
	if value := uimuo.created_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: useridmapping.FieldCreatedAt,
		})
	}
	if value := uimuo.modified_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: useridmapping.FieldModifiedAt,
		})
	}
	if value := uimuo.deleted_at; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: useridmapping.FieldDeletedAt,
		})
	}
	if uimuo.cleardeleted_at {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: useridmapping.FieldDeletedAt,
		})
	}
	if value := uimuo.platform_type; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  *value,
			Column: useridmapping.FieldPlatformType,
		})
	}
	if value := uimuo.platform_id; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: useridmapping.FieldPlatformID,
		})
	}
	if uimuo.clearedUser {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useridmapping.UserTable,
			Columns: []string{useridmapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uimuo.user; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useridmapping.UserTable,
			Columns: []string{useridmapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	uim = &UserIDMapping{config: uimuo.config}
	_spec.Assign = uim.assignValues
	_spec.ScanValues = uim.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uimuo.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return uim, nil
}
