// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jaredallard/grocerylistsbot/ent/predicate"
	"github.com/jaredallard/grocerylistsbot/ent/useridmapping"
)

// UserIDMappingDelete is the builder for deleting a UserIDMapping entity.
type UserIDMappingDelete struct {
	config
	predicates []predicate.UserIDMapping
}

// Where adds a new predicate to the delete builder.
func (uimd *UserIDMappingDelete) Where(ps ...predicate.UserIDMapping) *UserIDMappingDelete {
	uimd.predicates = append(uimd.predicates, ps...)
	return uimd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uimd *UserIDMappingDelete) Exec(ctx context.Context) (int, error) {
	return uimd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (uimd *UserIDMappingDelete) ExecX(ctx context.Context) int {
	n, err := uimd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uimd *UserIDMappingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: useridmapping.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useridmapping.FieldID,
			},
		},
	}
	if ps := uimd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uimd.driver, _spec)
}

// UserIDMappingDeleteOne is the builder for deleting a single UserIDMapping entity.
type UserIDMappingDeleteOne struct {
	uimd *UserIDMappingDelete
}

// Exec executes the deletion query.
func (uimdo *UserIDMappingDeleteOne) Exec(ctx context.Context) error {
	n, err := uimdo.uimd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useridmapping.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uimdo *UserIDMappingDeleteOne) ExecX(ctx context.Context) {
	uimdo.uimd.ExecX(ctx)
}
