// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// GroceryItem is the predicate function for groceryitem builders.
type GroceryItem func(*sql.Selector)

// GroceryList is the predicate function for grocerylist builders.
type GroceryList func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserIDMapping is the predicate function for useridmapping builders.
type UserIDMapping func(*sql.Selector)
